// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parking.Models;

namespace Parking.Migrations
{
    [DbContext(typeof(ParkingContext))]
    [Migration("20200606133455_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("Parking.Models.PriceTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FimVigencia")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InicioVigencia")
                        .HasColumnType("TEXT");

                    b.Property<float>("ValorHoraAdicional")
                        .HasColumnType("REAL");

                    b.Property<float>("ValorHoraInical")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("PriceTable");
                });

            modelBuilder.Entity("Parking.Models.VehicleControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Duracao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HoraEntrada")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HoraSaida")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("QtdHorasCobradas")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("ValorHora")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("VehicleControl");
                });
#pragma warning restore 612, 618
        }
    }
}
